### ISSUE TITLE
Provide a template engine that embeds PowerShell

### ISSUE THREAD

**Issue by aldrichtr** [aldrichtr/stencil#37]
There are a few template engines available for PowerShell, but they each have their "quirks" (that is subjective, I know).  I think that templates fit in with the design goal of stencil.

## Tasks
- [ ] Document the design goals of a template engine
- [ ] Implement a tokenizer / parser for stencil templates
- [ ] Convert template tokens to template objects on the pipeline
